#!/bin/bash

function error() {
    echo ""
    echo "ERROR | $@"
    echo ""
    exit 1
}

params=$@
[ -z "$params" ] && params="tests"

./redis-certify
ec="$?"
[ "${ec}" -eq 0 ] || exit $ec

./vendor/bin/phpunit --colors --testdox $params
